# -*- coding: utf-8 -*-
"""claude wiki crawler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WNTg1U8lpn0znqn2TSlNOydwbV6aY03

installs (run once)
"""

!pip install anthropic networkx --quiet

# imports and configs
import requests
import json
import time
import re
import anthropic

# ── Tweak these to control the crawl ─────────────────────────────────────────
ROOT_ARTICLE = "Robotics"   # starting article
MAX_DEPTH    = 2            # 0 = root only, 1 = root + children, 2 = recommended
MAX_LINKS    = 25           # links to follow per article (keeps runtime sane)
CHUNK_SIZE   = 3000         # characters per LLM prompt chunk
OUTPUT_FILE  = "robotics_knowledge_base.json"

# ── Anthropic client ──────────────────────────────────────────────────────────
# In Colab: store your key with  Secrets (🔑 icon) as ANTHROPIC_API_KEY
from google.colab import userdata
client = anthropic.Anthropic(api_key=userdata.get("ANTHROPIC_API_KEY"))

HEADERS = {
    "User-Agent": "HackathonProject/1.0 (nrapheal04@gmail.com)"
}

"""



 knowledge base skeleton

"""

# knowledge base skeleton
knowledge_base = {
    "articles":      {},   # title → metadata dict
    "relationships": [],   # all extracted (source, relation, target) triples
    "traversal":     []    # full crawl history, including revisits
}

visited_titles: set = set()

"""wikipedia api helpers"""

# wikipedia api helpers
def get_article_text(title: str) -> str:
    """Fetch the plain-text extract of a Wikipedia article."""
    url = (
        "https://en.wikipedia.org/w/api.php"
        "?action=query"
        "&prop=extracts"
        "&explaintext=1"
        "&format=json"
        f"&titles={requests.utils.quote(title)}"
    )
    try:
        r = requests.get(url, headers=HEADERS, timeout=15)
        r.raise_for_status()
        page = next(iter(r.json()["query"]["pages"].values()))
        return page.get("extract", "")
    except Exception as e:
        print(f"  ⚠  Text fetch failed for '{title}': {e}")
        return ""


def get_article_links(title: str) -> list:
    """Return Wikipedia article titles linked from the given article (main namespace only)."""
    url = (
        "https://en.wikipedia.org/w/api.php"
        "?action=query"
        "&prop=links"
        "&pllimit=max"
        "&plnamespace=0"   # main namespace: no Talk:, User:, File:, etc.
        "&format=json"
        f"&titles={requests.utils.quote(title)}"
    )
    try:
        r = requests.get(url, headers=HEADERS, timeout=15)
        r.raise_for_status()
        page = next(iter(r.json()["query"]["pages"].values()))
        return [lnk["title"] for lnk in page.get("links", [])]
    except Exception as e:
        print(f"  ⚠  Link fetch failed for '{title}': {e}")
        return []


def get_article_categories(title: str) -> list:
    """Return the categories the article belongs to."""
    url = (
        "https://en.wikipedia.org/w/api.php"
        "?action=query"
        "&prop=categories"
        "&cllimit=max"
        "&format=json"
        f"&titles={requests.utils.quote(title)}"
    )
    try:
        r = requests.get(url, headers=HEADERS, timeout=15)
        r.raise_for_status()
        page = next(iter(r.json()["query"]["pages"].values()))
        cats = [c["title"] for c in page.get("categories", [])]
        return [c.replace("Category:", "") for c in cats]  # strip prefix
    except Exception as e:
        print(f"  ⚠  Category fetch failed for '{title}': {e}")
        return []

"""year extratcion"""

# year extraction
_YEAR_RE = re.compile(r'\b(19[0-9]{2}|20[0-9]{2})\b')

def extract_years(text: str) -> list:
    """Pull all 4-digit years (1900–2099) mentioned in text."""
    return sorted(set(int(y) for y in _YEAR_RE.findall(text)))

"""LLM relationship extraction"""

# LLM relationship extraction
SYSTEM_PROMPT = (
    "You are a knowledge-graph extraction engine specialised in robotics "
    "and adjacent fields. Return ONLY valid JSON — no prose, no markdown fences."
)

RREL_PROMPT_TEMPLATE = REL_PROMPT_TEMPLATE = """\
Extract relationships from the following Wikipedia text about robotics.

Return ONLY a JSON array — no preamble, no markdown backticks:

[
  {{
    "source": "concise entity or concept",
    "relation": "verb or relation type",
    "target": "concise entity or concept"
  }}
]

Rules:
- Use concise noun-phrase entities (e.g. "LIDAR", "robot arm", "PID controller").
- Focus on meaningful robotics relationships: components, capabilities, inventors,
  applications, subfields, historical milestones, enabling technologies.
- Ignore vague or trivial relationships.
- Return up to 20 high-confidence relationships.

Text:
\"\"\"
{chunk}
\"\"\"
"""


def extract_relationships_llm(text: str, article_title: str) -> list:
    """
    Split text into chunks, send each to Claude, collect relationship triples.
    Returns a list of dicts: {source, relation, target, article}
    """
    all_rels = []
    # Cap at 5 chunks (15 000 chars) per article to keep costs predictable
    max_chars = CHUNK_SIZE * 5
    chunks = [
        text[i : i + CHUNK_SIZE]
        for i in range(0, min(len(text), max_chars), CHUNK_SIZE)
    ]

    for idx, chunk in enumerate(chunks):
        if len(chunk.strip()) < 100:
            continue
        try:
            msg = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=1024,
                system=SYSTEM_PROMPT,
                messages=[{
                    "role": "user",
                    "content": REL_PROMPT_TEMPLATE.format(chunk=chunk)
                }]
            )

            raw = msg.content[0].text.strip()
            raw = re.sub(r'^```(?:json)?\s*', '', raw)
            raw = re.sub(r'\s*```$', '', raw)
            # Normalize any line breaks that snuck in
            raw = raw.replace('\n', ' ')
            try:
                rels = json.loads(raw)
            except json.JSONDecodeError as e:
                print(f"     ⚠  Chunk {idx+1}: Parse failed: {e}")
                continue

            for r in rels:
                r["article"] = article_title
            all_rels.extend(rels)
            print(f"     chunk {idx+1}/{len(chunks)}: {len(rels)} relationships")
        except json.JSONDecodeError:
            print(f"     ⚠  Chunk {idx+1}: Claude returned non-JSON, skipping")
        except Exception as e:
            print(f"     ⚠  Chunk {idx+1} error: {e}")
        time.sleep(0.4)   # gentle rate-limiting

    return all_rels

"""core crawler"""

# core crawler
def crawl_article(title: str, parent=None, depth: int = 0):
    """
    Recursively crawl a Wikipedia article.

    - Always records the traversal path (even for revisits).
    - Processes each unique article exactly once.
    - Saves the knowledge base to disk after every article (crash-safe).
    """
    indent = "  " * depth

    # ── Step 1: record traversal (always, even revisits) ────────────────────
    knowledge_base["traversal"].append({
        "title":  title,
        "parent": parent,
        "depth":  depth
    })

    # ── Step 2: skip if already visited ──────────────────────────────────────
    if title in visited_titles:
        print(f"{indent}↩  {title}  (already visited)")
        return

    # ── Step 3: mark visited immediately ─────────────────────────────────────
    visited_titles.add(title)
    print(f"{indent}🔍  Visiting: {title}  (depth {depth})")

    # ── Step 4: fetch article text ────────────────────────────────────────────
    text = get_article_text(title)
    if not text:
        print(f"{indent}⚠   No text found — skipping.")
        return

    # ── Step 5: fetch metadata ─────────────────────────────────────────────
    categories    = get_article_categories(title)
    year_mentions = extract_years(text)

    # ── Step 6: LLM relationship extraction ──────────────────────────────────
    print(f"{indent}   Extracting relationships…")
    rels = extract_relationships_llm(text, title)
    knowledge_base["relationships"].extend(rels)
    print(f"{indent}   ✓ {len(rels)} relationships extracted")

    # ── Step 7: store article record ─────────────────────────────────────────
    knowledge_base["articles"][title] = {
        "title":          title,
        "depth":          depth,
        "parent":         parent,
        "text_length":    len(text),
        "categories":     categories,
        "year_mentions":  year_mentions,
        "relationships":  len(rels),
        "links_found":    0,        # filled in below if we recurse
        "processed":      True
    }

    # ── Step 8: persist (crash-safe checkpoint) ───────────────────────────────
    save_knowledge_base()

    # ── Step 9: stop recursing at max depth ──────────────────────────────────
    if depth >= MAX_DEPTH:
        return

    # ── Step 10: fetch child links and recurse ────────────────────────────────
    links = get_article_links(title)
    knowledge_base["articles"][title]["links_found"] = len(links)
    print(f"{indent}   Queueing {min(len(links), MAX_LINKS)} / {len(links)} links…\n")

    for child_title in links[:MAX_LINKS]:
        time.sleep(0.5)   # polite delay between requests
        crawl_article(child_title, parent=title, depth=depth + 1)

"""persistence helpers"""

# persistence helpers
def save_knowledge_base(path: str = OUTPUT_FILE):
    """Write the knowledge base to a JSON file."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(knowledge_base, f, indent=2, ensure_ascii=False)


def load_knowledge_base(path: str = OUTPUT_FILE) -> dict:
    """Load a previously saved knowledge base (useful for resuming)."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

"""networkX graph builder"""

# networkX graph builder
def build_graph(kb: dict = None):
    """
    Build a directed NetworkX graph from extracted relationships.

    Each edge carries:  relation, article
    Each node is a concise robotics concept / entity.
    """
    try:
        import networkx as nx
    except ImportError:
        print("networkx not installed — run:  !pip install networkx")
        return None

    if kb is None:
        kb = knowledge_base

    G = nx.DiGraph()
    for rel in kb["relationships"]:
        src = rel.get("source", "").strip()
        tgt = rel.get("target", "").strip()
        if src and tgt:
            G.add_node(src)
            G.add_node(tgt)
            G.add_edge(
                src, tgt,
                relation=rel.get("relation", ""),
                article=rel.get("article", "")
            )

    print(f"Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")
    return G


def top_nodes(G, n: int = 20):
    """Print the n most-connected nodes (by total degree)."""
    import networkx as nx
    ranked = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:n]
    print(f"\nTop {n} nodes by degree:")
    for name, deg in ranked:
        print(f"  {deg:>4}  {name}")

"""load and inspect the json dataset"""

# load and inspect the json dataset
kb = load_knowledge_base()

print(f"Articles: {len(kb['articles'])}")
print(f"Relationships: {len(kb['relationships'])}")
print(f"Traversal: {len(kb['traversal'])}\n")

print("─" * 60)
print("ARTICLES:")
print("─" * 60)
for title, meta in kb['articles'].items():
    print(f"\n{title}")
    print(f"  Depth: {meta['depth']}")
    print(f"  Categories: {', '.join(meta['categories'][:3]) if meta['categories'] else 'None'}")
    print(f"  Years mentioned: {meta['year_mentions'][:5] if meta['year_mentions'] else 'None'}")
    print(f"  Relationships extracted: {meta['relationships']}")

print("\n" + "─" * 60)
print("RELATIONSHIPS:")
print("─" * 60)
for i, rel in enumerate(kb['relationships'][:10]):  # first 10
    print(f"\n{i+1}. {rel['source']} → {rel['relation']} → {rel['target']}")
    print(f"   From: {rel['article']}")

"""Reset state before every crawl run"""

# Reset state before every crawl run
knowledge_base = {
    "articles":      {},
    "relationships": [],
    "traversal":     []
}
visited_titles = set()

"""run the crawl"""

# run the crawl
if __name__ == "__main__":
    print(f"Starting robotics knowledge-graph crawl")
    print(f"  Root     : {ROOT_ARTICLE}")
    print(f"  Max depth: {MAX_DEPTH}")
    print(f"  Max links: {MAX_LINKS}\n")

    crawl_article(ROOT_ARTICLE)

    save_knowledge_base()
    print("\n✅  Crawl complete!")
    print(f"   Articles crawled : {len(knowledge_base['articles'])}")
    print(f"   Relationships    : {len(knowledge_base['relationships'])}")
    print(f"   Traversal records: {len(knowledge_base['traversal'])}")

    G = build_graph()
    if G:
        top_nodes(G)